### ISSUE TITLE
Exception in thread Thread-1 (most likely raised during interpreter shutdown)

### ISSUE THREAD

**Issue by ru108** [wirenboard/wb-mqtt-db-cli#1]
```
wb-mqtt-db-cli.py -h 127.0.0.1 --from "2017-06-01" --to "2017-06-02" --decimal-places 2 -o file.csv  wb-adc/5Vout wb-adc/Vin
```
File created, but...

output:
```
Exception in thread Thread-1 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 754, in run
  File "/usr/lib/python2.7/dist-packages/mosquitto.py", line 2051, in _thread_main
  File "/usr/lib/python2.7/dist-packages/mosquitto.py", line 1174, in loop_forever
  File "/usr/lib/python2.7/dist-packages/mosquitto.py", line 720, in loop
  File "/usr/lib/python2.7/dist-packages/mosquitto.py", line 956, in loop_read
<type 'exceptions.TypeError'>: 'NoneType' object is not callable
```

Need add before csvfile.close()
https://github.com/wirenboard/wb-mqtt-db-cli/blob/69b4f42e89e0b402ab0d149f2c59798ad63dcbaa/wb-mqtt-db-cli.py#L176-L177

client.loop_stop()

**Comment by sikmir** [comment]
Fixed in #10
